ERROR 2025-07-09 11:49:25,612 log Internal Server Error: /randevu/tablo/
Traceback (most recent call last):
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\appointment_views.py", line 279, in appointment_table_partial
    return render(request, 'hastane/appointment_table_partial.html', {'appointments': appointments})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hastane/appointment_table_partial.html
ERROR 2025-07-09 11:49:25,619 basehttp "GET /randevu/tablo/ HTTP/1.1" 500 82223
ERROR 2025-07-09 13:16:53,347 log Internal Server Error: /randevu/ekle/
Traceback (most recent call last):
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\appointment_views.py", line 239, in appointment_create
    html = render_to_string('hastane/appointment_form.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hastane/appointment_form.html
ERROR 2025-07-09 13:16:53,347 basehttp "GET /randevu/ekle/?appointment_id=9 HTTP/1.1" 500 78506
ERROR 2025-07-09 13:16:53,784 log Internal Server Error: /randevu/ekle/
Traceback (most recent call last):
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\appointment_views.py", line 239, in appointment_create
    html = render_to_string('hastane/appointment_form.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hastane/appointment_form.html
ERROR 2025-07-09 13:16:53,784 basehttp "GET /randevu/ekle/?appointment_id=9 HTTP/1.1" 500 78506
ERROR 2025-07-09 13:16:53,984 log Internal Server Error: /randevu/ekle/
Traceback (most recent call last):
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\appointment_views.py", line 239, in appointment_create
    html = render_to_string('hastane/appointment_form.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hastane/appointment_form.html
ERROR 2025-07-09 13:16:53,984 basehttp "GET /randevu/ekle/?appointment_id=9 HTTP/1.1" 500 78506
ERROR 2025-07-09 13:16:54,142 log Internal Server Error: /randevu/ekle/
Traceback (most recent call last):
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\appointment_views.py", line 239, in appointment_create
    html = render_to_string('hastane/appointment_form.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hastane/appointment_form.html
ERROR 2025-07-09 13:16:54,142 basehttp "GET /randevu/ekle/?appointment_id=9 HTTP/1.1" 500 78506
ERROR 2025-07-09 13:16:57,321 log Internal Server Error: /randevu/ekle/
Traceback (most recent call last):
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\appointment_views.py", line 239, in appointment_create
    html = render_to_string('hastane/appointment_form.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: hastane/appointment_form.html
ERROR 2025-07-09 13:16:57,321 basehttp "GET /randevu/ekle/?appointment_id=9 HTTP/1.1" 500 78526
ERROR 2025-07-09 13:45:32,394 log Internal Server Error: /randevu/doktor-uygunluk/7/
Traceback (most recent call last):
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\appointment_views.py", line 124, in check_doctor_availability
    'speciality': doctor.speciality
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'Doctors' object has no attribute 'speciality'
ERROR 2025-07-09 13:45:32,512 basehttp "GET /randevu/doktor-uygunluk/7/?date=2025-07-31&time=11%3A00&appointment_id=9 HTTP/1.1" 500 69319
ERROR 2025-07-31 15:40:23,970 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base_login.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\login_views.py", line 6, in login_select_view
    return render(request, 'loginpage/login_select.html')
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base_login.html
ERROR 2025-07-31 15:40:23,970 basehttp "GET / HTTP/1.1" 500 126730
ERROR 2025-07-31 15:48:00,278 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 170, in render
    return self._render(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 162, in _render
    return self.nodelist.render(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 938, in render
    bit = node.render_annotated(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 905, in render_annotated
    return self.render(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base_login.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\login_views.py", line 6, in login_select_view
    return render(request, 'loginpage/login_select.html')
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base_login.html
ERROR 2025-07-31 15:48:00,285 basehttp "GET / HTTP/1.1" 500 126730
ERROR 2025-07-31 18:47:15,830 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 148: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:15,834 basehttp "GET / HTTP/1.1" 500 138593
ERROR 2025-07-31 18:47:34,559 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:34,559 basehttp "GET / HTTP/1.1" 500 138715
ERROR 2025-07-31 18:47:35,143 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:35,143 basehttp "GET / HTTP/1.1" 500 138715
ERROR 2025-07-31 18:47:35,305 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:35,305 basehttp "GET / HTTP/1.1" 500 138715
ERROR 2025-07-31 18:47:35,879 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:35,879 basehttp "GET / HTTP/1.1" 500 138715
ERROR 2025-07-31 18:47:39,853 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:39,859 basehttp "GET / HTTP/1.1" 500 138708
ERROR 2025-07-31 18:47:40,509 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:40,509 basehttp "GET / HTTP/1.1" 500 138708
ERROR 2025-07-31 18:47:40,692 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:40,692 basehttp "GET / HTTP/1.1" 500 138708
ERROR 2025-07-31 18:47:40,958 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:40,960 basehttp "GET / HTTP/1.1" 500 138708
ERROR 2025-07-31 18:47:41,251 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:41,251 basehttp "GET / HTTP/1.1" 500 138708
ERROR 2025-07-31 18:47:41,425 log Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 470, in parse
    compile_func = self.tags[command]
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\index_views.py", line 12, in index_view
    return render(request, 'index.html', context)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 472, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\template\base.py", line 531, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 155: 'static'. Did you forget to register or load this tag?
ERROR 2025-07-31 18:47:41,425 basehttp "GET / HTTP/1.1" 500 138708
ERROR 2025-07-31 20:03:12,963 log Internal Server Error: /login/doctor/
Traceback (most recent call last):
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\venv310\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\asuma\OneDrive\Masaüstü\HastaneYonetimProjesi\hastane\views\login_views.py", line 39, in doctor_login_view
    password_check_result = check_password(password, doctor.password)
AttributeError: 'Doctors' object has no attribute 'password'
ERROR 2025-07-31 20:03:12,963 basehttp "POST /login/doctor/ HTTP/1.1" 500 70970
